### ISSUE TITLE
Add Comment Data to Database

### ISSUE THREAD

**Issue by zohaibshahzadkhan** [zohaibshahzadkhan/SocialVibe-API#1]
**Description:**
 
As a backend developer, I should be able to add the comment data in the database so that the user's data is reflected accurately.
(Related Epic: https://github.com/zohaibshahzadkhan/SocialVibe-React-App/issues/23)

**Acceptance Criteria:**

- An endpoint exists to handle the Create comment request (PUT <uuid:pk>/comment/).
- If the user is authorized, the comment is added in the database.
- The endpoint returns a success response with the updated post with comment data.

**Comment by 7AXEL** [comment]
Check out this project: https://github.com/7AXEL/Web2APK
